### ISSUE TITLE
caiman実行エラー

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#341]
添付の構成のworkflow(caiman)の実行時、エラーが発生していることを確認。

![Image](https://github.com/arayabrain/barebone-studio/assets/122338895/2ffed142-4f49-4608-b896-f34500b668a4)

### 詳細

- エラーログ（caiman_mc）
```
Traceback (most recent call last):
  File "/home/user/workspaces/optinist/studio/app/common/core/rules/runner.py", line 48, in run
    output_info = cls.execute_function(
  File "/home/user/workspaces/optinist/studio/app/common/core/rules/runner.py", line 134, in execute_function
    output_info = func(
  File "/home/user/workspaces/optinist/studio/app/optinist/wrappers/caiman/motion_correction.py", line 56, in caiman_mc
    extract_binary_masks_from_structural_channel(
  File "/home/user/workspaces/optinist/.snakemake/conda/ad2fad2dce3c33285c3868f3b3ae6ddc_/lib/python3.8/site-packages/caiman/base/rois.py", line 141, in extract_binary_masks_from_structural_channel
    temp = dilation(temp, selem=selem)
  File "/home/user/workspaces/optinist/.snakemake/conda/ad2fad2dce3c33285c3868f3b3ae6ddc_/lib/python3.8/site-packages/skimage/morphology/misc.py", line 38, in func_out
    return func(image, footprint=footprint, *args, **kwargs)
TypeError: dilation() got an unexpected keyword argument 'selem'
```

- 環境
  - 動作環境: ubuntu 22.04
  - アプリケーション: optinist v1.2.1 (github版、pypi版)

- 補足
  - エラーは入力データの長さによらず発生
  - なお以下の環境では、正常動作を確認
    - Mac環境
    - barebone-studio 版

**Comment by itutu-tienday** [comment]
以下、エラー原因を確認

■原因
caiman の requirements.txt で指定されているモジュールの一部で、バージョン不整合がある模様
https://github.com/flatironinstitute/CaImAn/blob/main/requirements.txt
・OK環境）scikit-image 0.19.x
・NG環境）scikit-image 0.20.0

■対策
※検討中
