### ISSUE TITLE
[Onboarding]Test code specification confirmation

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#373]

**Comment by tsuchiyama-araya** [comment]
Python テストについてを調べる。

https://realpython.com/python-testing/

**Comment by tsuchiyama-araya** [comment]
Python テスト

Python では、dict（「辞書」の略）は、キーと値のペアのコレクションを格納するための組み込みデータ型です。辞書はデータを効率的に整理およびアクセスするのに非常に便利です。

test_expt_reader.py
* read関数はExptConfig型を返します。
* exp_configの内容
    * workspace_id -> str
    * unique_id -> str
    * started_at -> str
    * Name -> str
    * Function -> dict（これはPythonの辞書型）
    * function[input_0] unique_id -> str
    * function[input_0] name -> str
    * function[input_0] success -> str

test_expt_writer.py
* Create Config関数のテスト
* 実行情報ステータスがRunningであることのテスト
* Configを読み取りExpt_Config関数に変換するテスト
* 新しい書き込みのテスト
    * WorkflowConfigが必要
    * 実験を実行し、出力をYAMLファイルに書き込む
* Write Addのテスト -> 新しい書き込みテストとの違いは？

test_snakemake_executor.py
* snakemakeを実行するには、workspace_id、unique_id、smk_paramを渡す必要がある
* 依存関係を削除 -> smkparamを設定するだけでいいのか？
* test_error_snakemake_execute -> snakemakeがエラーの場合、エラーファイルが作成される

test_workflow_reader.py
* 最初にワークフローファイルを読み込み、nodeDictとedgeDictを取得する
* nodeDictとedgeDictを読み取る

test_workflow_result.py　-> こちらのテストコードはあんまり理解ができないです。
* ワークフロー結果では、実行時に作成されたファイルを統合する

**Comment by tsuchiyama-araya** [comment]
可能であれば、test_workflow_resultについて、どなたか一緒に見れたら、お願いしたいです。

**Comment by tsuchiyama-araya** [comment]
【残タスク】

- [ ] エラーしているところの洗い出し
努力目標 -> テスト必要そうな部分を探してみる（テストカバレッジも理解する）

**Comment by tsuchiyama-araya** [comment]
【出会ったエラー】
`2024-07-12 15:37:18,336 INFO:     [snakemake.logging] text_handler():510 -
Traceback (most recent call last):
  File "/app/.snakemake/scripts/tmpg0mv4yw2.func.py", line 30, in <module>
    rule_config = RuleConfigReader.read(snakemake.params.name)
  File "/app/studio/app/common/core/snakemake/snakemake_reader.py", line 15, in read
    matPath=rule["matPath"],
KeyError: 'matPath'
2024-07-12 15:37:23,643 ERROR:    [snakemake] smk_logger():91 - {'level': 'debug', 'msg': 'Full Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2561, in run_wrapper\n    run(\n  File "/app/studio/app/Snakefile", line 101, in __rule_4\n  File "/usr/local/lib/python3.8/site-packages/snakemake/script.py", line 1567, in script\n    executor.evaluate()\n  File "/usr/local/lib/python3.8/site-packages/snakemake/script.py", line 455, in evaluate\n    self.execute_script(fd.name, edit=edit)\n  File "/usr/local/lib/python3.8/site-packages/snakemake/script.py", line 683, in execute_script\n    self._execute_cmd(\n  File "/usr/local/lib/python3.8/site-packages/snakemake/script.py", line 486, in _execute_cmd\n    return shell(\n  File "/usr/local/lib/python3.8/site-packages/snakemake/shell.py", line 294, in __new__\n    raise sp.CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command \'set -euo pipefail;  /usr/local/bin/python3 /app/.snakemake/scripts/tmpg0mv4yw2.func.py\' returned non-zero exit status 1.\n', 'timestamp': 1720766243.642449}`

`Error in rule suite2p_file_convert:
    jobid: 2
    input: studio/test_data/output/default/snakemake/input_0/data_endoscope.pkl
    output: studio/test_data/output/default/snakemake/suite2p_file_convert/suite2p_file_convert.pkl
    conda-env: /app/.snakemake/conda/0f05ef6e0614bb486f644bea8d4b33d4_

2024-07-12 15:37:23,667 ERROR:    [snakemake.logging] text_handler():550 - Error in rule suite2p_file_convert:
    jobid: 2
    input: studio/test_data/output/default/snakemake/input_0/data_endoscope.pkl
    output: studio/test_data/output/default/snakemake/suite2p_file_convert/suite2p_file_convert.pkl
    conda-env: /app/.snakemake/conda/0f05ef6e0614bb486f644bea8d4b33d4_`

**Comment by tsuchiyama-araya** [comment]
上記の問題に関しては、一応Issueを作成しました。
そのため、こちらのIssueは一旦完了かと思いますが、ご確認お願いいたします。

上記のIssue：
https://github.com/arayabrain/barebone-studio/issues/387
