### ISSUE TITLE
Nested button error

### ISSUE THREAD

**Issue by milesAraya** [arayabrain/barebone-studio#379]
**追加機能についての概要**
Front end error however, does not seem to effect DOM function
Appears when using `docker compose -f docker-compose.dev.yml up`
```
react-dom.development.js:86 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at http://localhost:3000/static/js/bundle.js:40022:66
    at ButtonBase (http://localhost:3000/static/js/bundle.js:50683:82)
    at http://localhost:3000/static/js/bundle.js:40022:66
    at IconButton (http://localhost:3000/static/js/bundle.js:58157:83)
    at ParamSettingDialog (http://localhost:3000/static/js/bundle.js:9665:3)
    at button
    at http://localhost:3000/static/js/bundle.js:40022:66
    at ButtonBase (http://localhost:3000/static/js/bundle.js:50683:82)
    at http://localhost:3000/static/js/bundle.js:40022:66
    at IconButton (http://localhost:3000/static/js/bundle.js:58157:83)
    at span
    at Tooltip (http://localhost:3000/static/js/bundle.js:74215:83)
    at div
    at http://localhost:3000/static/js/bundle.js:40022:66
    at ButtonGroup (http://localhost:3000/static/js/bundle.js:51771:83)
    at div
    at FileSelectImple (http://localhost:3000/static/js/bundle.js:10105:3)
    at FileSelect (http://localhost:3000/static/js/bundle.js:10018:3)
    at div
    at http://localhost:3000/static/js/bundle.js:40022:66
    at Box (http://localhost:3000/static/js/bundle.js:79370:72)
    at div
    at NodeContainer (http://localhost:3000/static/js/bundle.js:12307:3)
    at BehaviorFileNodeImple (http://localhost:3000/static/js/bundle.js:9393:7)
    at BehaviorFileNode (http://localhost:3000/static/js/bundle.js:9374:181)
    at div
    at NodeWrapper (http://localhost:3000/static/js/bundle.js:472106:5)
    at div
    at NodeRenderer (http://localhost:3000/static/js/bundle.js:472519:7)
    at div
    at Viewport (http://localhost:3000/static/js/bundle.js:473298:3)
    at div
    at http://localhost:3000/static/js/bundle.js:471430:3
    at div
    at ZoomPane (http://localhost:3000/static/js/bundle.js:470993:3)
    at FlowRenderer (http://localhost:3000/static/js/bundle.js:472366:3)
    at GraphView (http://localhost:3000/static/js/bundle.js:473470:3)
    at Wrapper (http://localhost:3000/static/js/bundle.js:473976:3)
    at div
    at http://localhost:3000/static/js/bundle.js:474015:3
    at div
    at ReactFlowProvider (http://localhost:3000/static/js/bundle.js:473964:3)
    at div
    at ReactFlowComponent (http://localhost:3000/static/js/bundle.js:12535:77)
    at main
    at http://localhost:3000/static/js/bundle.js:40022:66
    at DndProvider (http://localhost:3000/static/js/bundle.js:494626:7)
    at div
    at http://localhost:3000/static/js/bundle.js:40022:66
    at Box (http://localhost:3000/static/js/bundle.js:79370:72)
    at FlowChart (http://localhost:3000/static/js/bundle.js:8381:76)
    at div
    at http://localhost:3000/static/js/bundle.js:40022:66
    at Box (http://localhost:3000/static/js/bundle.js:79370:72)
    at div
    at TabPanel (http://localhost:3000/static/js/bundle.js:27400:5)
    at div
    at http://localhost:3000/static/js/bundle.js:40022:66
    at Workspace (http://localhost:3000/static/js/bundle.js:27338:104)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:431579:5)
    at Routes (http://localhost:3000/static/js/bundle.js:432201:5)
    at main
    at http://localhost:3000/static/js/bundle.js:40022:66
    at div
    at http://localhost:3000/static/js/bundle.js:40022:66
    at Box (http://localhost:3000/static/js/bundle.js:79370:72)
    at http://localhost:3000/static/js/bundle.js:40022:66
    at div
    at http://localhost:3000/static/js/bundle.js:40022:66
    at Box (http://localhost:3000/static/js/bundle.js:79370:72)
    at http://localhost:3000/static/js/bundle.js:40022:66
    at AuthedLayout (http://localhost:3000/static/js/bundle.js:3869:3)
    at Layout (http://localhost:3000/static/js/bundle.js:3811:3)
    at Router (http://localhost:3000/static/js/bundle.js:432139:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:430199:5)
    at SnackbarProvider (http://localhost:3000/static/js/bundle.js:231087:24)
    at App (http://localhost:3000/static/js/bundle.js:760:76)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:78007:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:78600:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:76280:14)
    at Provider (http://localhost:3000/static/js/bundle.js:427375:3)
    ```

**重要度**
この機能の重要度を[低、中、高]に分ける。
低: この機能は開発要件の最低条件に含まれていない。

**ブランチ名**
develop-main

**その他**
Will add more comments once I have tested in other environments

**Comment by tsuchiyama-araya** [comment]
実装＆テスト - 1
レビュー＆指摘修正 - 0.5

**Comment by tsuchiyama-araya** [comment]
現在発生しているかを確認して、特に発生していないであれば、Closeします。

**Comment by milesAraya** [comment]
CsvParamSettingDialog was previously rendered as a child of another IconButton. Looking at the current code in         
  FileSelect.tsx:253-262, the CsvParamSettingDialog is wrapped in <Tooltip><span>...</span></Tooltip> — not inside an IconButton. The <span> wrapper is correct and prevents the nested button issue.
