### ISSUE TITLE
During Backend Test Error Happens

### ISSUE THREAD

**Issue by tsuchiyama-araya** [arayabrain/barebone-studio#387]
When I do make test_run which runs frontend and backend tests.
During backend test it passes but these things shows into the log.

```
2024-07-12 15:37:18,336 INFO:     [snakemake.logging] text_handler():510 -
Traceback (most recent call last):
  File "/app/.snakemake/scripts/tmpg0mv4yw2.func.py", line 30, in <module>
    rule_config = RuleConfigReader.read(snakemake.params.name)
  File "/app/studio/app/common/core/snakemake/snakemake_reader.py", line 15, in read
    matPath=rule["matPath"],
KeyError: 'matPath'
2024-07-12 15:37:23,643 ERROR:    [snakemake] smk_logger():91 - {'level': 'debug', 'msg': 'Full Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2561, in run_wrapper\n    run(\n  File "/app/studio/app/Snakefile", line 101, in __rule_4\n  File "/usr/local/lib/python3.8/site-packages/snakemake/script.py", line 1567, in script\n    executor.evaluate()\n  File "/usr/local/lib/python3.8/site-packages/snakemake/script.py", line 455, in evaluate\n    self.execute_script(fd.name, edit=edit)\n  File "/usr/local/lib/python3.8/site-packages/snakemake/script.py", line 683, in execute_script\n    self._execute_cmd(\n  File "/usr/local/lib/python3.8/site-packages/snakemake/script.py", line 486, in _execute_cmd\n    return shell(\n  File "/usr/local/lib/python3.8/site-packages/snakemake/shell.py", line 294, in __new__\n    raise sp.CalledProcessError(retcode, cmd)\nsubprocess.CalledProcessError: Command \'set -euo pipefail;  /usr/local/bin/python3 /app/.snakemake/scripts/tmpg0mv4yw2.func.py\' returned non-zero exit status 1.\n', 'timestamp': 1720766243.642449}
```

```
Error in rule suite2p_file_convert:
    jobid: 2
    input: studio/test_data/output/default/snakemake/input_0/data_endoscope.pkl
    output: studio/test_data/output/default/snakemake/suite2p_file_convert/suite2p_file_convert.pkl
    conda-env: /app/.snakemake/conda/0f05ef6e0614bb486f644bea8d4b33d4_
```

```
2024-07-12 15:37:23,667 ERROR:    [snakemake.logging] text_handler():550 - Error in rule suite2p_file_convert:
    jobid: 2
    input: studio/test_data/output/default/snakemake/input_0/data_endoscope.pkl
    output: studio/test_data/output/default/snakemake/suite2p_file_convert/suite2p_file_convert.pkl
    conda-env: /app/.snakemake/conda/0f05ef6e0614bb486f644bea8d4b33d4_
```

**Comment by itutu-tienday** [comment]
closed due to content already reported in #373
