### ISSUE TITLE
[Cloud Support] Resolving CaImAn errors on AWS ECS

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#440]
The following error occurs when running CaImAn in AWS ECS environment.
Countermeasures are needed.

```
ERROR - smk_status_logger.py -
{'level': 'debug', 'msg': 'Full Traceback (most recent call last):\n
  File "/root/.cache/pypoetry/virtualenvs/optinist-9TtSrW0h-py3.8/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 576, in create\n
    out = create_env(env_file, filetype="yaml")\n
  File "/root/.cache/pypoetry/virtualenvs/optinist-9TtSrW0h-py3.8/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 538, in create_env\n
    out = shell.check_output(\n
  File "/root/.cache/pypoetry/virtualenvs/optinist-9TtSrW0h-py3.8/lib/python3.8/site-packages/snakemake/shell.py", line 61, in check_output\n
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)\n
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output\n
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run\n
    raise CalledProcessError(retcode, process.args,\n
subprocess.CalledProcessError: Command \'conda env create --quiet --file "/app/.snakemake/conda/23a0fcc13df369566a15cf65d2b25641_.yaml" --prefix "/app/.snakemake/conda/23a0fcc13df369566a15cf65d2b25641_"\' died with <Signals.SIGKILL: 9>.\n
\n
During handling of the above exception, another exception occurred:\n
\n
Traceback (most recent call last):\n
  File "/root/.cache/pypoetry/virtualenvs/optinist-9TtSrW0h-py3.8/lib/python3.8/site-packages/snakemake/__init__.py", line 771, in snakemake\n
    success = workflow.execute(\n
  File "/root/.cache/pypoetry/virtualenvs/optinist-9TtSrW0h-py3.8/lib/python3.8/site-packages/snakemake/workflow.py", line 924, in execute\n
    dag.create_conda_envs(\n
  File "/root/.cache/pypoetry/virtualenvs/optinist-9TtSrW0h-py3.8/lib/python3.8/site-packages/snakemake/dag.py", line 349, in create_conda_envs\n
    env.create(dryrun)\n
  File "/root/.cache/pypoetry/virtualenvs/optinist-9TtSrW0h-py3.8/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 595, in create\n
    raise CreateCondaEnvironmentException(\n
snakemake.exceptions.CreateCondaEnvironmentException: Could not create conda environment from /app/studio/app/optinist/wrappers/caiman/conda/caiman.yaml:\n
Command:\n
conda env create --quiet --file "/app/.snakemake/conda/23a0fcc13df369566a15cf65d2b25641_.yaml" --prefix "/app/.snakemake/conda/23a0fcc13df369566a15cf65d2b25641_"\n
Output:\n
Collecting package metadata (repodata.json): ...working... \n
', 'timestamp': 1714061661.5794506}
```

- Note
  - The error rate is 100% at the time of issue creation.
  - No similar errors have occurred with other algorithms (suite2p, etc.).

**Comment by itutu-tienday** [comment]
Probably due to lack of memory in the execution environment (ECS container).
Increased memory (from 3GB to 8GB) and confirmed that the error was suppressed.

- Error message
  - > Collecting package metadata (repodata.json): / Killed
- Reference page
  - https://stackoverflow.com/questions/64821441/collecting-package-metadata-repodata-json-killed
  - https://github.com/conda/conda/issues/9728
  - https://blog.zhenyulincs.com/2023/12/19/problem-collecting-package-metadata-repodata-json-killed/

- Other
  - If swap can be created, it seems possible to take measures at low cost, but since swap is not available for the Fargate type (it is available for the EC2 type), direct memory expansion is necessary.

- Subsequent Tasks
  - [ ] Verification of optimal memory values (probably at least 6 GB)
