### ISSUE TITLE
[Cloud Support] Support for uploading Edit ROI results to S3

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#445]
### Features

- [x] Support for uploading Edit ROI results to S3

#### Bugs

- [x] Edit Edit ROI ROI Runtime Runtime Error Error
```
Traceback (most recent call last):
File "/workspacesd/barebone-studio-cloud/.snakemake/scripts/tmpexi1n5ri.edit_ROI.py", line 20, in <module>
EditROI(file_path=config["file_path"]).commit()
File "/workspacesd/barebone-studio-cloud/studio/app/optinist/core/edit_ROI/edit_ROI.py", line 228, in commit
self.__update_whole_nwb(info)
File "/workspacesd/barebone-studio-cloud/studio/app/optinist/core/edit_ROI/edit_ROI.py", line 272, in __update_whole_nwb
Runner.save_all_nwb(whole_nwb_path, last_output_info["nwbfile"])
File "/workspacesd/barebone-studio-cloud/studio/app/common/core/rules/runner.py", line 115, in save_all_nwb
input_nwbfile = all_nwbfile["input"]
KeyError: 'input'
```

**Comment by itutu-tienday** [comment]
> - Edit ROI Runtime Error

- fixed at c49fe3a
