### ISSUE TITLE
[No.203]Workflow を新しいIDでcopy する機能

### ISSUE THREAD

**Issue by tsuchiyama-araya** [arayabrain/barebone-studio#487]
### 【内容】
実装画面　→ RECORD画面

「RUN ALL」を実行すれば同じワークフローを作成できることは理解しているが、再実行が必要なため時間がかかる。
そのため、実行状態を保持したまま、新しいIDや名前でワークフローをコピーできる機能が欲しい。
Reproduce機能の一つのオプションとして実装するのが適切だと思われる。
→ 右上のDeleteボタンの横に「Duplicate」ボタンを追加する。

- https://docs.google.com/spreadsheets/d/1x0vizVJK8U0GXuZyDPap0g-iri7xDX19/edit?gid=260426401#gid=260426401
  - No.203

### 【実装流れ】

- [x] 資料作成（デザイン、実装提案）
- [x] 上司に実装提案のレビュー
- [x] 実装する
- [x] テストを実施

### 完了条件

- [x] Duplicateボタンが確認できる
- [x] Duplicateボタンをクリックすると、新しいIDで同じWorkflowを作成できる
- [ ] 内部レビューの完了

**Comment by tsuchiyama-araya** [comment]
suite2p のCopyは完了

# 【問題】
- CaimanのCopyは失敗
## caiman_mc
```
Traceback (most recent call last):

  File "/app/studio/app/common/core/rules/runner.py", line 48, in run
    output_info = cls.execute_function(

  File "/app/studio/app/common/core/rules/runner.py", line 134, in execute_function
    output_info = func(

  File "/app/studio/app/optinist/wrappers/caiman/motion_correction.py", line 100, in caiman_mc
    shutil.move(mmap_file, mmap_output_dir)

  File "/app/.snakemake/conda/50197191c5309552067cdbe522d3702d_/lib/python3.8/shutil.py", line 789, in move
    raise Error("Destination path '%s' already exists" % real_dst)

shutil.Error: Destination path '/app/studio_data/output/24/a26d32ee/caiman_mc_p4f6nsi9bh/mmap/sample_mouse2p_image_rig__d1_128_d2_128_d3_1_order_F_frames_2000_.mmap' already exists
``` 

## caiman_cnmf
```
Traceback (most recent call last):

  File "/app/studio/app/common/core/rules/runner.py", line 34, in run
    input_info = cls.read_input_info(__rule.input)

  File "/app/studio/app/common/core/rules/runner.py", line 155, in read_input_info
    assert PickleReader.check_is_valid_node_pickle(

AssertionError: Invalid node input data content. [/app/studio_data/output/24/a26d32ee/caiman_mc_p4f6nsi9bh/caiman_mc.pkl]
``` 

## pca
```
Traceback (most recent call last):

  File "/app/studio/app/common/core/rules/runner.py", line 34, in run
    input_info = cls.read_input_info(__rule.input)

  File "/app/studio/app/common/core/rules/runner.py", line 155, in read_input_info
    assert PickleReader.check_is_valid_node_pickle(

AssertionError: Invalid node input data content. [/app/studio_data/output/24/a26d32ee/caiman_cnmf_qcjcwx9uq7/caiman_cnmf.pkl]
```
