### ISSUE TITLE
[No.81]Improved FAQs for errors

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/barebone-studio#515]
### requirement
  - https://docs.google.com/spreadsheets/d/1M5Ub_yRGM4DCltG01OHWssC7QrhJqDSY/
    - No.81

**Comment by tsuchiyama-araya** [comment]
メモ
・過去のIssueなどもこちらで記載する

**Comment by itutu-tienday** [comment]
- error:
  - situation: when caiman is executed in workflow (may be similar for *other wrapper func)
  - error log: `python /app/.snakemake/scripts/xxxxxxxxxxx.func.py\' died with <Signals.SIGKILL: 9>.`
- cause:
  - probably the workflow execution process is out of memory.
- related:
  - arayabrain/optinist-for-server#344

**Comment by itutu-tienday** [comment]
- error:
  - situation: When a workflow is executed in which the size of the node's processing result data (.pkl) is large (e.g., a large image + caiman)
  - error.log:
    ```
    Traceback (most recent call last):
      File "/app/studio/app/common/routers/run.py", line 72, in run_result
        return WorkflowResult(workspace_id, uid).get(nodeDict.pendingNodeIdList)
      File "/app/studio/app/common/core/workflow/workflow_result.py", line 58, in get
        node_result = NodeResult(
      File "/app/studio/app/common/core/workflow/workflow_result.py", line 150, in __init__
        self.info = PickleReader.read(pickle_filepath)
      File "/app/studio/app/common/core/utils/pickle_handler.py", line 13, in read
        return pickle.load(f)
    _pickle.UnpicklingError: pickle data was truncated
   ```
- cause:
  - When the size of the pkl file exceeds several GB (4GB?), an exception is suspected to occur during pickle read.
- countermeasure:
  - *Not yet considered

**Comment by itutu-tienday** [comment]
Note:
It is better to prepare a separate spreadsheet summarizing the error cases to work from.

**Comment by milesAraya** [comment]
Idea：when an error message comes (e.g. parameter problem), link to documentation comes up in error message

**Comment by milesAraya** [comment]
Why does first time loading take a long time
A: Making conda env

**Comment by tsuchiyama-araya** [comment]
https://github.com/arayabrain/barebone-studio/issues/365
こちらの問題の解消方法
Rosettaの設定をOffにしたら、Docker環境回復しました！

しかし、調査したところ、Rosettaの設定をOnにする時にも解消される時があるので、
自分の環境によって異なるかと思います。

![Image](https://github.com/user-attachments/assets/e078ecb5-c9b9-415e-8258-0d6888038ef3)

**Comment by milesAraya** [comment]
mysql error, alembic head upgrade not working
solution: delete all tables in mysql
run  alembic head upgrade
[re-add user initial data](https://optinist.readthedocs.io/en/latest/other/host_for_multiuser/setup.html#insert-initial-data)

**Comment by milesAraya** [comment]
https://github.com/oist/optinist/wiki/FAQ

**Comment by tsuchiyama-araya** [comment]
Tensorflowのインストール問題解決（原因は文字列が長すぎて、制限されている）

こちらでやり方はちがいますが、3. **「長いパスを有効にする」** を **「有効」** に設定する。
こちらの設定を有効したら、Caiman通りました。
下記のやり方で実行しました
**Windows Homeで長いパスを有効にする手順**

レジストリエディターを開く
1.) Windowsキー + R を押し、「regedit」と入力して Enterキー を押します。
ユーザーアカウント制御 (UAC) の確認画面が表示されたら、「はい」をクリックします。

2.) 以下のパスに移動する
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
LongPathsEnabledエントリを探す
右側のウィンドウで LongPathsEnabled を探します。

3.1) 存在する場合 → 次の手順へ進む。
3.2) 存在しない場合 → 以下の手順で作成：
右側の空白部分を 右クリック する。
「新規」 > 「DWORD (32 ビット) 値」 を選択。
「LongPathsEnabled」 と名前を付ける。

4.) LongPathsEnabledの値を変更する
LongPathsEnabled をダブルクリック。
「値のデータ」 を 0 → 1 に変更。
OK をクリック。
変更を適用する
